// Generated by CoffeeScript 1.7.1
(function() {
  var tpl, tpl1, tpl2;

  tpl = '<div tw-text="text">\n</div>\n<p tw-text="content"></p>\n<p>this is inline {{content}} bind.<input tw-value="content"/></p>\n<p>this is inline {{it.content}} bind and {{content}} bind.</p>\n<p tw-if="showIt"><span tw-text="it.content"></span><span tw-text="showIt"></span> is true</p>';

  tpl1 = '<div tw-repeat="peoples">this is {{content}}  and {{name}}.<p tw-text="content"></p><p tw-text="name"></p><div tw-repeat="pens"><p tw-text="color"></p></div></div>';

  tpl2 = '<div tw-text="it.text">\n</div>\n<p tw-text="it.content"></p>\n<p tw-text="it.content"></p>\n<p tw-text="that.content"></p>';

  window.onload = function() {
    var test1, test2, test3;
    test1 = function() {
      var domTpl, o;
      domTpl = Backbone.tinywing(tpl);
      domTpl.appendTo(document.body);
      o = {
        text: 'something like this',
        content: 'more',
        showIt: false,
        it: {
          content: 'it.content'
        }
      };
      return domTpl.render(o);
    };
    test2 = function() {
      var domTpl1, o;
      domTpl1 = Backbone.tinywing(tpl1);
      domTpl1.appendTo(document.body);
      o = {
        peoples: [
          {
            content: 'xxx',
            name: 'yyyy',
            pens: []
          }, {
            content: 'xxx',
            name: 'yyy',
            pens: []
          }
        ]
      };
      return domTpl1.render(o);
    };
    test3 = function() {
      var domTpl, o;
      domTpl = Backbone.tinywing(tpl2);
      domTpl.appendTo(document.body);
      o = {
        it: {
          text: 'it.xxxx',
          content: 'it.xxxxxx'
        },
        that: {
          content: 'that.xxxxx'
        }
      };
      return domTpl.render(o);
    };
    test1();
    test2();
    return test3();
  };

}).call(this);
